
variables:
  MONO_VERSION: 5_16_0
  XCODE_VERSION: 10.1

jobs:

  - job: build_windows
    displayName: Build on Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - powershell: .\build.ps1
        displayName: Run build

  - job: build_macos
    displayName: Build on macOS
    pool:
      vmImage: macos-10.13
    steps:
      - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
        displayName: Switch to the latest Xamarin SDK
      - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
        displayName: Switch to the latest Xcode
      - bash: sh ./build.sh
        displayName: Run build
